/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsUi_libIndexRouteImport } from './routes/projects/ui_lib/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsUi_libIndexRoute = ProjectsUi_libIndexRouteImport.update({
  id: '/projects/ui_lib/',
  path: '/projects/ui_lib/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/ui_lib/': typeof ProjectsUi_libIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/ui_lib': typeof ProjectsUi_libIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/ui_lib/': typeof ProjectsUi_libIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/' | '/projects/ui_lib/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects' | '/projects/ui_lib'
  id: '__root__' | '/' | '/projects/' | '/projects/ui_lib/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsUi_libIndexRoute: typeof ProjectsUi_libIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/ui_lib/': {
      id: '/projects/ui_lib/'
      path: '/projects/ui_lib'
      fullPath: '/projects/ui_lib/'
      preLoaderRoute: typeof ProjectsUi_libIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsUi_libIndexRoute: ProjectsUi_libIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
